image: maven:3.6.1

pipelines:
  default:
    - step:
        name: "Lint and run tests"
        caches:
          - maven
          - node
        script:
          - mvn -B verify # -B batch mode makes Maven less verbose
