version: '3'

services:

  jira:
    image: atlassian/jira-software
    depends_on:
      - postgresql
    ports:
      - '2990:8080'
    environment:
      - 'ATL_JDBC_URL=jdbc:postgresql://postgresql/jiradb'
      - 'ATL_JDBC_USER=jiradb'
      - 'ATL_JDBC_PASSWORD=password'
      - 'ATL_DB_DRIVER=org.postgresql.Driver'
      - 'ATL_DB_TYPE=postgres72'
      - 'ATL_TOMCAT_CONTEXTPATH=/jira'

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_USER=jiradb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
