AWSTemplateFormatVersion: 2010-09-09
Description: Jira / Confluence Server to DC (AWS) Helper

Resources:
  #S3 Bucket for Database Transfer
  MigrationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'atl-migrationbucket-${AWS::StackName}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Delete

  MigrationQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 864000
      FifoQueue: true
      QueueName: !Sub 'atl-migration-queue-${AWS::StackName}'
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 90

