AWSTemplateFormatVersion: 2010-09-09
Description: Jira / Confluence Server to DC (AWS) Helper

Resources:

  MigrationBucket:
    Type: AWS::S3::Bucket
    DependsOn: QueuePolicy
    Properties:
      BucketName: !Sub 'atl-migrationbucket-${AWS::StackName}'
      AccessControl: BucketOwnerFullControl
      NotificationConfiguration:
        QueueConfigurations:
          - Queue: !GetAtt MigrationQueue.Arn
            Event: s3:ObjectCreated:*
    DeletionPolicy: Delete



  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: !Sub "MigrationQueue_Policy_${AWS::AccountId}"
        Version: 2012-10-17
        Statement:
          - Sid: "MigrationQueue_SendMessage_Bucket"
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - SQS:SendMessage
            Resource: !GetAtt MigrationQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Join ["", ["arn:aws:s3:::",!Sub 'atl-migrationbucket-${AWS::StackName}']]
      Queues:
        - !Ref MigrationQueue

  MigrationQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5
      MessageRetentionPeriod: 864000
      QueueName: !Sub 'atl-migration-queue-${AWS::StackName}'
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 43200

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 864000
      QueueName: !Sub 'atl-migration-dlq-${AWS::StackName}'
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 43200

  StackNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /config/migration-helper/cloud.aws.stack.name
      Type: String
      Value: !Ref AWS::StackName
      Description: CloudFormation Stack Name

  JiraFilePathParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /config/migration-helper/app.jira.file.path
      Type: String
      Value: "atl-migration-queue-migration-helper"
      Description: File Path

  VPCIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /config/migration-helper/app.vpc.id
      Type: String
      Value: "vpc-02a66f2c3b0b1f599"
      Description: Helper VPC Id

  RegionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /config/migration-helper/app.region.id
      Type: String
      Value: !Ref AWS::Region
      Description: Region Name